# Generated by Django 4.1.2 on 2022-10-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="color",
            field=models.CharField(default="blue", max_length=40),
        ),
    ]
